project:
  type: website
  output-dir: docs

manuscript:
  article: index.qmd

format:
  html:
    self-contained: true
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  echo: true
  cache: false
  freeze: true


