project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd
  notebooks:
    - notebook: docs/index-preview.html
      title: Flight in Flux

format:
  html:
    self-contained: true
    comments:
      hypothesis: true
  docx: default
  jats: default

  # (other formats)
  # pdf: default

execute:
  echo: true
  cache: false
  freeze: true


